version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: .docker/backend/Dockerfile
    ports:
      - '4000:3000'
    depends_on:
      - mysql
    volumes:
      - './backend:/var/www'
    tty: true
    stdin_open: true
  mysql:
    image: 'mysql:8.0.32'
    ports:
      - '4306:3306'
    environment:
      MYSQL_DATABASE: 'lesson-docker-nestjs'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_USER: 'lesson-docker-nestjs'
      MYSQL_PASSWORD: 'password'
    volumes:
      - 'db:/var/lib/mysql'
volumes:
  db:
    driver: local